In [1]:
import pdb
import numpy as np
import matplotlib.pyplot as plt

def strip_new_line_char(string):
    ""
    if "\n" in string:
        return string[:-1]
    return string

In [7]:
subject = 'c746'

sensoryStd = 0.29
subjectArray = np.zeros((100,7))

file_parameters = open("auditory_categorization_prolific_online_data/preprocess_results/90-3000_100%_logPerceptAndLogLatent_GoFrom-InfToInf/results_from_cluster/resultsProlificData/errorbarsOnRelevanceMetric/"+subject+'.txt',"w")
for iterations in range(1,101):
    file_dev = "auditory_categorization_prolific_online_data/preprocess_results/90-3000_100%_logPerceptAndLogLatent_GoFrom-InfToInf/results_from_cluster/resultsProlificData/ControlResults/subsampledData/results_"+subject+'_'+str(iterations)+'.txt'
    with open(file_dev, 'r') as f:
        filelines = f.readlines()   
    fileArray = np.zeros((1,7))
    iline = 0
    while iline < len(filelines):
        if filelines[iline].startswith('[') and filelines[iline].endswith(']\n'):
            lineWithNewLineChar = strip_new_line_char(filelines[iline])
            lineElements = lineWithNewLineChar.split(",")
            temp = np.zeros((1,7))
            temp[:,6] = float(lineElements[6][:-1])
            temp[:,5] = float(lineElements[5][:-2])
            temp[:,4] = float(lineElements[4][:])
            temp[:,3] = float(lineElements[3][:])
            temp[:,2] = float(lineElements[2][:])
            temp[:,1] = float(lineElements[1][:])
            temp[:,0] = float(lineElements[0][8:])
            fileArray = np.append(fileArray,temp,axis=0)
            #print(fileArray[:,iline], iline)
            #pdb.set_trace()
            iline += 1
        else:
            line1WithNewLineChar = strip_new_line_char(filelines[iline])
            lineElementsOfFirstLine = line1WithNewLineChar.split(",")
            line2WithNewLineChar = strip_new_line_char(filelines[iline+1])
            lineElementsOfSecondLine = line2WithNewLineChar.split(",")
            lineElements = lineElementsOfFirstLine[:-1] + lineElementsOfSecondLine
            temp = np.zeros((1,7))
            temp[:,6] = float(lineElements[6][:-1])
            temp[:,5] = float(lineElements[5][:-2])
            temp[:,4] = float(lineElements[4][:])
            temp[:,3] = float(lineElements[3][:])
            temp[:,2] = float(lineElements[2][:])
            temp[:,1] = float(lineElements[1][:])
            temp[:,0] = float(lineElements[0][8:])
            #print(line1WithNewLineChar, line2WithNewLineChar, lineElements)
            #print(fileArray[:,iline], iline)
            fileArray = np.append(fileArray,temp,axis=0)
            iline += 2 
    
    fileArraySSConstrained_upperlimit = fileArray[fileArray[:,3]<sensoryStd+0.03]
    fileArraySSConstrained_lowerlimit = fileArraySSConstrained_upperlimit[fileArraySSConstrained_upperlimit[:,3]>sensoryStd-0.03]
    subjectArray[iterations-1,:] = fileArraySSConstrained_lowerlimit[np.argmin(fileArraySSConstrained_lowerlimit[:,-1])]
    file_parameters.write(str(np.around(subjectArray[iterations-1,:-1],decimals=2))+'\n')
    print(np.around(subjectArray[iterations-1,:-1],decimals=2))
    #pdb.set_trace()


[2.22 3.19 0.05 0.26 0.45 0.47]
[2.26 3.16 0.05 0.26 0.47 0.45]
[2.25 3.17 0.05 0.29 0.45 0.46]
[2.26 3.1  0.05 0.26 0.46 0.47]
[2.26 3.17 0.05 0.26 0.47 0.45]
[2.27 3.11 0.05 0.26 0.47 0.45]
[2.2  3.23 0.06 0.26 0.42 0.43]
[2.28 3.13 0.05 0.27 0.47 0.47]
[2.3  3.2  0.06 0.27 0.5  0.33]
[2.26 3.13 0.05 0.26 0.47 0.49]
[2.29 3.08 0.04 0.26 0.5  0.47]
[2.25 3.17 0.05 0.26 0.47 0.45]
[2.33 3.12 0.05 0.27 0.51 0.41]
[2.36 3.04 0.04 0.27 0.53 0.42]
[2.27 3.12 0.05 0.26 0.47 0.47]
[2.23 3.14 0.05 0.26 0.46 0.47]
[2.25 3.15 0.05 0.26 0.45 0.48]
[2.28 3.13 0.05 0.27 0.48 0.46]
[2.12 3.24 0.06 0.28 0.37 0.43]
[2.25 3.18 0.05 0.26 0.44 0.46]
[2.33 3.12 0.05 0.3  0.47 0.44]
[2.3  3.12 0.05 0.27 0.46 0.47]
[2.17 3.11 0.04 0.26 0.37 0.59]
[2.24 3.17 0.05 0.28 0.47 0.48]
[2.65 2.78 0.05 0.26 0.47 0.5 ]
[2.24 3.16 0.05 0.26 0.49 0.48]
[2.29 3.15 0.05 0.26 0.46 0.44]
[2.27 3.11 0.05 0.26 0.46 0.46]
[2.29 3.12 0.05 0.26 0.45 0.47]
[2.23 3.05 0.05 0.28 0.37 0.66]
[2.26 3.14 0.05 0.26 0.46 0.47]
[2.27 3.

In [ ]:
print("Mean",np.around(np.mean(subjectArray[:iterations-1],axis=0),decimals=2))
print("Std",np.around(np.std(subjectArray[:iterations-1],axis=0),decimals=2))
print("Median pback",np.around(np.quantile(subjectArray[:iterations-1,4],q=0.5),decimals=2))
print("5th quantile pback",np.around(np.quantile(subjectArray[:iterations-1,4],q=0.05),decimals=2))
print("95th quantile pback",np.around(np.quantile(subjectArray[:iterations-1,4],q=0.95),decimals=2))
print("Median LL",np.around(np.quantile(subjectArray[:iterations-1,-1]*6/6,q=0.5),decimals=2))
print("5th quantile LL",np.around(np.quantile(subjectArray[:iterations-1,-1]*6/6,q=0.05),decimals=2))
print("95th quantile LL",np.around(np.quantile(subjectArray[:iterations-1,-1]*6/6,q=0.95),decimals=2))
